Include `dom` to the `lib` compiler option
This fixes the error
```
% tsc -p ./
src/extension.ts:11:2 - error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'.

11  console.log('Congratulations, your extension "ucl-rsdg" is now active!');
    ~~~~~~~

Found 1 error.
```